export enum MessageStepEnum {
  FIRST_MESSAGE_STEP = "FIRST_MESSAGE_STEP",
  USERNAME_STEP = "USERNAME_STEP",
  CPF_STEP = "CPF_STEP",
  CEP_STEP = "CEP_STEP",
  OPTIONS_STEP = "OPTIONS_STEP",
  COMMAND_OPTION_STEP = "COMMAND_OPTION_STEP"
}
